### ISSUE TITLE
Cannot add a comment via the Eclipse Juno SR1.

### ISSUE THREAD

**Issue by charleech** [danmunn/redmine_mylyn_connector#15]
Hi,

My Redmine information is as the following: -

Environment:
  Redmine version                          2.2.2.stable
  Ruby version                             1.9.3 (x86_64-linux)
  Rails version                            3.2.11
  Environment                              production
  Database adapter                         Mysql2

Redmine plugins:
  jredmine                                 1.5.1
  redmine_mylyn_connector                  2.8.2.stable

I can update the issue status, but cannot add the comment through the Eclipse. The Redmine log told me as the following: -

Started PUT "/redmine/issues/3073.xml" for 127.0.0.1 at 2013-02-19 15:18:20 +0700
Processing by IssuesController#update as XML
  Parameters: {"..."}
WARNING: Can't verify CSRF token authenticity
  Current user: charlee.ch (id=3)
  Rendered text template (0.0ms)

Could you please help to advise further? Thank you very much for your help in advance. I'm looking forward to hearing from you soon.

Regards,

Charlee Ch.

**Comment by poulls** [comment]
I have the same redmine coniguration with u, but can't even update status. The only thing can do is attaching files into redmine issues from eclipse mylyn.
Which eclipse mylyn plugin did you use to link redmine?

**Comment by charleech** [comment]
Hi,

I'm using Eclipse Juno SR1 with the Mylyn Connector: Redmine 0.3.7 with fresh workspace.

**Comment by poulls** [comment]
I'm using the same connector. 

Here is redmine log I got when update status from eclipse:
Started PUT "/redmine/issues/1.xml?key=7ba73bc927e950ab2b4a94f850682ebdfbd592dd" for 196.123.132.68 at 2013-02-21 10:49:58 +0800
Processing by IssuesController#update as XML
  Parameters: {"key"=>"7ba73bc927e950ab2b4a94f850682ebdfbd592dd", "id"=>"1"}
WARNING: Can't verify CSRF token authenticity
  Current user: mshui (id=4)
  Rendered text template (0.0ms)
Completed 200 OK in 98ms (Views: 1.7ms | ActiveRecord: 15.6ms)

No error message poped up but only a warning there, issue status didn't change in redmine. I'm not sure it is a bug of redmine plugin or eclipse mylyn connector. Is there a way to figure out what's wrong here?

**Comment by charleech** [comment]
Hi,
I'm trying to use the steps mentioned at [HowTo connect a Mylyn repository to Redmine](http://www.redmine.org/projects/redmine/wiki/howto_mylyn) by following the [Using the generic web repository connector](http://www.redmine.org/projects/redmine/wiki/howto_mylyn#Using-the-generic-web-repository-connector)

Please take a note, I'm also installing the Mylyn related plug-ins to my Eclipse as well. It would be better if you backup the current Eclipse first. Here is the [Snapshot Builds update site](http://download.eclipse.org/mylyn/incubator/3.8) for Eclipse 3.6, 3.7, 3.8, 4.2.

It will provide the web interface for integrating to the Redmine. When opening the mylyn task, there is a web interface (as same as we've seen via the web browser). I can log in and use it as a web, together with private planing and context (there is another tabs as well).

This may be an alternative and suitable way instead of using the specific connector.

**Comment by awilkins** [comment]
The warning is a red herring - I patched the plugin to pass the token back in the correct header - the warning goes away but the notes still don't update. For me the estimated time and status fields work at least. From other bugs on the Red mine tracker, I think the REST API may be broken -  the method failing is not a Mylyn connector method but part of the REST API.

**Comment by jeeeyul** [comment]
+1

**Comment by rolandstoll** [comment]
+1

**Comment by awilkins** [comment]
This has been fixed in the ljader fork of the Mylyn plugin. The API has changed due to changes in either Redmine in the 2.x series or underlying Ruby components. The way the plugin called the stock Redmine API was a little off and the API is now less tolerant.

Thanks to the work of ljader on Mavenizing the build, it's really easy to pull the sources and get an update site after an `mvn clean package`

**Comment by rolandstoll** [comment]
confused: the ljader fork of the MyLyn plugin is 2 years old, the danmunn MyLyn plugin is 4-10 month old...

**Comment by charleech** [comment]
Please correct me If I'm wrong. I understand that it is https://github.com/ljader/redmine-mylyn-plugin which is active 10 days ago.

**Comment by awilkins** [comment]
I think there's some naming confusion here ;

There are two parts to this ; there is a plugin for Redmine that is written in Ruby and lives on the server ; it provides extra RPC methods for the use of ....

The Mylyn connector for Redmine, which lives on the client. 

The problem described in this issue is with this client part - not the server code in this repository. The problem is with how it calls a standard Redmine RPC method, not with the methods in the extra APIs provided by this code, so the appropriate fix is in the Mylyn part.

https://github.com/ljader/redmine-mylyn-plugin

Somewhere along the line (back with the old Sourceforge project I think) the naming conventions got crossed over. The part for Mylyn is usually called a connector, the part for Redmine is called a plugin, but the code repositories are named the other way around.

This branch of the server code is the most up to date and the one I use myself.

**Comment by rolandstoll** [comment]
thanks for the explanation!

So https://github.com/ljader/redmine-mylyn-plugin is a replacement for the eclipse-mylyn-redmine-connector... right? (someone really should correct the confusing names... ^^).

Is there also a eclipse update site available for https://github.com/ljader/redmine-mylyn-plugin (similar to http :// redmin-mylyncon.sourceforge.net/update-site/N/)? Honestly I don't know how to put all the source files to the expected jar files. And an update site would make the integration in the eclipse plugin manager so much easier...

**Comment by rumahherbal1** [comment]
thank you for the information, <a href="http://goo.gl/s0jCVC"> Obat Diabetes </a>we respect each other and visit each other by exchanging link..insha Allah four months

**Comment by rumahherbal1** [comment]
thank you for the information, we respect each other and visit each other by exchanging link..insha Allah four months
<a href="http://goo.gl/EVS5H7">obat taradisional kanker payudara</a>
<a href="http://goo.gl/IsyVTR">obat stroke </a>
<a href="http://goo.gl/PGkxmk"> obat jantung koroner</a>
<a href="http://hargaobatacemaxs.com/obat-tradisional-miom-kronis/"> Obat tradisional miom</a>
